# Generated by Django 5.0.7 on 2024-09-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('e_mail', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
    ]
