# Generated by Django 5.0.7 on 2024-09-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_ecom1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='id',
            new_name='user_id',
        ),
    ]
