# Generated by Django 5.0.7 on 2024-10-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_orders_cart_id_orderdetails'),
        ('users', '0007_accounts_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_mode', models.CharField(max_length=50)),
                ('date_of_payment', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accounts')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsDetails',
            fields=[
                ('payment_id', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='payments.payments', verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentmode', models.CharField(max_length=50)),
            ],
        ),
    ]
