# Generated by Django 5.0.7 on 2024-10-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='PaymentsDetails',
        ),
    ]
