# Generated by Django 5.0.7 on 2024-10-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payments_order_id_delete_paymentsdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='Payment_mode',
            new_name='payment_mode',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(default='online', max_length=20),
            preserve_default=False,
        ),
    ]
