# Generated by Django 5.0.7 on 2024-09-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.TextField(default='n/a'),
        ),
    ]
