# Generated by Django 5.0.7 on 2024-09-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='user_first_name', max_length=20)),
                ('lastname', models.CharField(default='user_last_name', max_length=20)),
                ('e_mail', models.EmailField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
    ]
