# Generated by Django 5.0.7 on 2024-10-30 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='user_first_name', max_length=20)),
                ('lastname', models.CharField(default='user_last_name', max_length=20)),
                ('e_mail', models.EmailField(max_length=20, unique=True)),
                ('phone_no', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(default='N/A', max_length=200, unique=True)),
                ('cart_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Address_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=200)),
                ('colony', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('Cart_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accounts')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
            ],
        ),
    ]
