# Generated by Django 5.0.7 on 2024-10-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='Cart_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='customer_id',
        ),
    ]
