# Generated by Django 5.0.7 on 2024-09-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='e_mail',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
