# Generated by Django 5.0.7 on 2024-10-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_cart_id_carts_id_remove_address_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='cart_id',
        ),
    ]
