# Generated by Django 5.0.7 on 2024-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accounts_e_mail_alter_accounts_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='password',
            field=models.CharField(default='N/A', max_length=20, unique=True),
        ),
    ]
