# Generated by Django 5.0.7 on 2024-10-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accounts_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='cart_id',
            field=models.IntegerField(default=None, max_length=20),
        ),
    ]
