# Generated by Django 5.0.7 on 2024-10-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_accounts_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='cart_id',
            field=models.IntegerField(default=None),
        ),
    ]
