# Generated by Django 5.0.7 on 2024-10-30 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('shop', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('shipping_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('payment_status', models.CharField(max_length=20)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.carts')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payments')),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
