# Generated by Django 5.0.7 on 2024-10-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shop', '0003_products_stock'),
        ('users', '0007_accounts_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.carts'),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.orders')),
                ('quantity', models.IntegerField(default=1, max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
            ],
        ),
    ]
