# Generated by Django 5.0.7 on 2024-10-29 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_cart_id_orderdetails'),
        ('payments', '0002_remove_payments_order_id_delete_paymentsdetails'),
        ('users', '0007_accounts_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='cart_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.carts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='payment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.payments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(default='Online', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(default='successful', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
