# Generated by Django 5.0.7 on 2024-10-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderdetails_amount_remove_orders_cart_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_status',
        ),
    ]
